### ISSUE TITLE
Using released BERT pre-trained weights

### ISSUE THREAD

**Issue by Colanim** [Separius/BERT-keras#1]
Awesome job that you did !

Do you plan implementing the BERT pre-trained weights, now that they are released ?

**Comment by Separius** [comment]
Yes, hopefully by the end of the day it will be ready, you can check the
progress (and help) in "Import" branch of the code.
I was able to load the weights (Bert uses an extra layer norm, so I had to
add it) but currently the results are different and I didn't dig deep into
it, I will do it as soon as possible

**Comment by Colanim** [comment]
Amazing !

I will take a look as soon as possible, thanks for the direction

**Comment by Separius** [comment]
You can now import the pretrained models into this library (theano is not working, I will try to fix it as soon as possible)
