### ISSUE TITLE
ValueError: You need tensorflow >= 1.3 for better keras tpu support!

### ISSUE THREAD

**Issue by astariul** [Separius/BERT-keras#13]
When running the example notebook (on Colab), I receive the following error :

> ValueError: You need tensorflow >= 1.3 for better keras tpu support!

This error appear when I execute :

`g_bert.compile('adam', 'mse')`

Any idea from where it comes from ?

---

I checked the version of Tensorflow with :

`!pip list | grep tensorflow`

And it gives me an expected result :

> mesh-tensorflow          0.0.5                
tensorflow               1.12.0               
tensorflow-hub           0.2.0                
tensorflow-metadata      0.9.0                
tensorflow-probability   0.5.0   

@HighCWu

**Comment by HighCWu** [comment]
This seems to be my fault, I forgot to correct the previous misuse, now the colab pip install code has been fixed @Colanim

**Comment by Colanim** [comment]
Thanks you @HighCWu for your quick fix ! 

---

Now I have another problem :
When executing this line with TPU :

`from transformer import refresh_keras_backend`

The runtime die, I don't really know why.

---

I will check if it's working with GPU

**Comment by HighCWu** [comment]
Glad you solved this problem so you can close this issue. If you have some new problems, you can open a new issue @Colanim
