### ISSUE TITLE
Does it have chinese version?

### ISSUE THREAD

**Issue by Zhengxuru** [Separius/BERT-keras#24]
I wanna a Chinese version BERT-keras, does it exist?

**Comment by Separius** [comment]
yes you should be able to load any [pretrained model](https://github.com/google-research/bert#pre-trained-models)

but it seems that the Chinese version is not that great you can a take a look at [this](https://github.com/PaddlePaddle/LARK/tree/develop/ERNIE) from baidu (sadly it's not in keras though)

disclaimer: I'm not chinese and what I said is based on baidu's blog post :))
